### ISSUE TITLE
InvalidArgumentError: slice index 7 of dimension 4 out of bounds.

### ISSUE THREAD

**Issue by XinhuiLi** [denbonte/CER3BRUM#2]
Hi,

I used Colab GPU to train the model now but I encountered another issue:

InvalidArgumentError: slice index 7 of dimension 4 out of bounds. for '{{node metrics_1/average_dice_coef_multilabel/strided_slice_16}} = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=15, ellipsis_mask=0, end_mask=15, new_axis_mask=0, shrink_axis_mask=16](main_output_1/truediv, metrics_1/average_dice_coef_multilabel/strided_slice_16/stack, metrics_1/average_dice_coef_multilabel/strided_slice_16/stack_1, metrics_1/average_dice_coef_multilabel/strided_slice_16/stack_2)' with input shapes: [?,256,320,320,7], [5], [5], [5] and with computed input tensors: input[1] = <0 0 0 0 7>, input[2] = <0 0 0 0 8>, input[3] = <1 1 1 1 1>.

Have you ever seen this issue by any chance? My modified notebook and full error message can be found here:
https://github.com/SucyLi/CER3BRUM/blob/master/src/CEREBRUM_notebook_training_colab.ipynb

Thanks so much for your help!

**Comment by denbonte** [comment]
Dear Xinhui,

`Have you ever seen this issue by any chance?`

I'm sorry to see you're experiencing problems. Unfortunately, we did not test the code on Colab: all the development, training and testing was carried out exploiting machines _in loco_.

Hoping this can be useful, I wanted to mention we used Python 2.7, Keras 2.2.2 and Tensorflow-GPU 1.9.0, at the time.

**Comment by XinhuiLi** [comment]
Hi Dennis,

I found that my issue was caused by these lines:
https://github.com/denbonte/CER3BRUM/blob/master/src/cer3brum_lib/fullyvol/cer3brum.py#L530-L539

It can run after I uncomment `model.compile(loss = loss_function, optimizer = my_adam, metrics=['categorical_crossentropy'])` and comment out 

```
model.compile(loss = losses_dict[loss_function],
                               optimizer = my_adam,
                               metrics = ['categorical_crossentropy',
                               losses_dict['multiclass_dice_coeff'],
                               losses_dict['average_multiclass_dice_coeff'],
                               #losses_dict['weighted_multiclass_dice_coeff'],
                               losses_dict['tanimoto_coefficient'] ])
```
Do you think it's a reasonable solution?

**Comment by denbonte** [comment]
Dear Xinhui,

> Do you think it's a reasonable solution?

Indeed! It could be that some code I wrote regarding the losses (specified in the lines you commented out) is not compatible with newer version of Keras/TF!

Personally, I would try to fix at least the Dice Coefficient loss function (probably right now there are plenty implementations that you can find for `tf` or `tf.keras` on GitHub), so that you can either train using that or (I'd say most importantly) pass it to the `compile` function as an element of `metrics` (the `categorical_crossentropy` loss, computed on the training and tuning set, makes you able to control for overfitting - but it's far from interpretable if you're trying to understand the actual performance of the model; the Dice Coefficient, on the other hand, is way more informative in my opinion).

Furthermore, just so that you know, in our experience training from scratch with the DC didn't turn out to be the best solution. I'd rather try to train the model exploiting the categorical crossentropy loss before, and then maybe fine-tune it using the DC.

Have a nice week start!
Dennis.

**Comment by XinhuiLi** [comment]
Dank u! Really appreciate your detailed explanation.
